# Generated by Django 2.1.1 on 2018-10-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_time',
            new_name='published_date',
        ),
    ]
